import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { migrateHealth, saveProfile, saveLab, saveGroceryItem, getHealth } from '../core/health.mjs';
import { generateMealWeek, createMealService, getMealWeek, buildMealGroceries, mealGroceries } from '../core/meal-planner.mjs';
import { setShoppingItemState } from '../core/shopping.mjs';
const config = { model: { protocol: 'openai', baseUrl: 'http://127.0.0.1:11434/v1', model: 'nemotron-3-nano:30b' }, mail: [{ secret: 'PRIVATE_MAIL_SENTINEL' }] };
const input = { weekStart: '2026-09-14', servings: 1, maxMinutes: 45, instructions: '' };
function fixture(t, profile = {}) { const db = new DatabaseSync(':memory:'); db.exec('CREATE TABLE kv(k TEXT PRIMARY KEY,v TEXT)'); migrateHealth(db); saveProfile(db, { goals: 'Varied meals', diet: 'none', allergies: 'none', householdSize: 1, weeklyBudget: 80, ...profile }); t.after(() => db.close()); return db; }
import { samplePlan } from './helpers/meal-fixture.mjs';

const reply = value => ({text:JSON.stringify(value),stopReason:'stop'});
const make = (db, value = samplePlan(), extra = {}) => generateMealWeek({ db, config, input, complete:async()=>reply(value), ...extra });
function persist(db, week) { db.prepare('INSERT OR REPLACE INTO kv(k,v) VALUES(?,?)').run(`shopping.meals.${week.weekStart}`,JSON.stringify(week)); }
const build = (db,week,selectedIds=['0-breakfast'],extra={}) => buildMealGroceries(db,{weekStart:week.weekStart,weekId:week.id,expectedRevision:week.revision,selectedIds,...extra});

test('local model receives fresh health facts, never mail; no saved records change during suggestion generation',async t=>{
 const db=fixture(t);saveLab(db,{id:'lipids',date:'2026-09-10',name:'Saved test',value:'208',unit:'mg/dL',referenceHigh:200});
 let request;const before=JSON.stringify(getHealth(db));const week=await make(db,samplePlan(),{complete:async r=>{request=r;return reply(samplePlan());}});
 assert.equal(week.meals.length,21);assert.equal(week.recipes.length,9);assert.equal(week.sources.find(s=>s.id==='lab:lipids').value,'208');
 assert.match(request.messages[0].content,/Saved test/);assert.doesNotMatch(JSON.stringify(request),/PRIVATE_MAIL_SENTINEL/);assert.equal(request.localRuntime,'ollama');assert.equal(request.json,true);assert.equal(JSON.stringify(getHealth(db)),before);assert.deepEqual(week.selectedIds,[]);
});
test('remote inference is rejected before any health data leaves',async t=>{const db=fixture(t);let calls=0;await assert.rejects(make(db,samplePlan(),{config:{model:{...config.model,baseUrl:'https://api.example.com/v1'}},complete:()=>{calls++;}}),/local model/);assert.equal(calls,0);});
test('unknown allergies stay unknown and recorded exclusions are enforced',async t=>{const db=fixture(t,{allergies:''});const w=await make(db);assert.equal(getMealWeek(db,input.weekStart).profile.allergies,'');assert.equal(w.sources.some(s=>s.id==='profile:allergies'),false);saveProfile(db,{allergies:'peanuts'});const p=samplePlan();p.recipes[0].ingredients[0].name='Peanut butter';await assert.rejects(make(db,p),/excluded/);});
test('diet exclusions, medical claims and invented source references are rejected',async t=>{const db=fixture(t,{diet:'vegan'});for(const edit of [p=>p.recipes[0].ingredients[0].name='Chicken',p=>p.recipes[0].reason='This will cure your condition',p=>p.recipes[0].basisIds=['lab:invented']]) {const p=samplePlan();edit(p);await assert.rejects(make(db,p));}});
test('quantities, costs, cooking limits and exact complete week are validated',async t=>{const db=fixture(t);for(const edit of [p=>p.recipes[0].minutes=90,p=>p.recipes[0].ingredients[0].costHigh=0,p=>p.recipes[0].ingredients[0].quantity=-1,p=>p.recipes[0].slot='invalid',p=>p.recipes.pop(),p=>p.recipes[0].id=p.recipes[1].id]) {const p=samplePlan();edit(p);await assert.rejects(make(db,p));}});
test('health changes during generation invalidate the result',async t=>{const db=fixture(t);await assert.rejects(make(db,samplePlan(),{complete:async()=>{saveLab(db,{name:'New record',date:'2026-09-11',value:'4'});return reply(samplePlan());}}),/health information changed/);});
test('consolidates quantities and price ranges only for selected meals, with compatible conversions',async t=>{const db=fixture(t);const p=samplePlan();p.recipes[0].ingredients[0].quantity=.05;p.recipes[0].ingredients[0].unit='kg';const week=await make(db,p);const groups=mealGroceries(week,['0-breakfast','0-lunch']);const rice=groups.find(g=>g.name==='Brown rice (dry)');assert.equal(rice.quantity,100);assert.equal(rice.unit,'g');assert.equal(rice.costLow,40);assert.equal(rice.costHigh,80);assert.equal(groups.length,3);assert.throws(()=>mealGroceries(week,['0-breakfast','0-breakfast']));});
test('building persists meals and groceries atomically, retries never duplicate, manual items survive',async t=>{const db=fixture(t);const manual=saveGroceryItem(db,{name:'My own item',quantity:'2 item',state:'needed'}).item;const w=await make(db);persist(db,w);const result=build(db,w,['0-breakfast','0-lunch']);assert.equal(result.groceryCount,3);assert.equal(getHealth(db).plans[0].entries.length,2);assert.equal(getHealth(db).groceryItems.length,4);const before=JSON.stringify(getHealth(db));assert.equal(build(db,w,['0-breakfast','0-lunch']).unchanged,true);assert.equal(JSON.stringify(getHealth(db)),before);const next=build(db,result.week,[]);assert.equal(next.groceryCount,0);assert.deepEqual(getHealth(db).groceryItems.map(i=>i.id),[manual.id]);});
test('cross-device revision and source changes prevent stale writes',async t=>{const db=fixture(t);const w=await make(db);persist(db,w);const saved=build(db,w);assert.throws(()=>build(db,w,['0-lunch']),/another device/);saveLab(db,{date:'2026-09-12',name:'Updated lab',value:'1'});assert.throws(()=>build(db,saved.week,['0-lunch']),/health information changed/);});
test('recipe swaps stay in their meal slot and change list contents without duplicated quantities',async t=>{const db=fixture(t);const p=samplePlan();p.recipes[1].ingredients[0].name='Quinoa (dry)';const w=await make(db,p);persist(db,w);assert.throws(()=>build(db,w,['0-breakfast'],{choices:{'0-breakfast':'r6'}}),/matching meal/);const result=build(db,w,['0-breakfast'],{choices:{'0-breakfast':'r1'}});assert.equal(getHealth(db).groceryItems.some(i=>i.name==='Quinoa (dry)'),true);assert.equal(build(db,w,['0-breakfast'],{choices:{'0-breakfast':'r1'}}).unchanged,true);assert.equal(result.week.meals[0].recipeId,'r1');});
test('preserves pantry status for unchanged amounts; protected user edits are not overwritten',async t=>{const db=fixture(t);const w=await make(db);persist(db,w);let saved=build(db,w);const item=getHealth(db).groceryItems[0];setShoppingItemState(db,{id:item.id,expectedUpdatedAt:item.updatedAt,state:'have'});saved=build(db,saved.week,['1-breakfast']);assert.equal(getHealth(db).groceryItems.find(i=>i.id===item.id).state,'have');const edited=getHealth(db).groceryItems[0];saveGroceryItem(db,{...edited,quantity:'999 g'});assert.throws(()=>build(db,saved.week,['2-breakfast']),/edited elsewhere/);});
test('background planning survives caller disconnects, prevents overlap, saves completed weeks',async t=>{const db=fixture(t),localWork=new Set();let release,calls=0;const gate=new Promise(r=>release=r);const service=createMealService({db,config:()=>config,localWork,generate:async args=>{calls++;await gate;return make(db);}});assert.equal(service.start(input).job.status,'running');assert.equal(service.start(input).job.status,'running');await Promise.resolve();assert.equal(calls,1);assert.equal(localWork.size,1);const done=[...localWork][0].done;release();await done;assert.equal(service.get(input.weekStart).job.status,'complete');assert.equal(service.get(input.weekStart).week.meals.length,21);assert.equal(localWork.size,0);});
test('cancellation and restart recovery keep the previous saved week',async t=>{const db=fixture(t),localWork=new Set(),w=await make(db);persist(db,w);const service=createMealService({db,config:()=>config,localWork,generate:async({signal})=>{await new Promise((resolve,reject)=>{if(signal.aborted)reject(new Error());else signal.addEventListener('abort',()=>reject(new Error()),{once:true});});}});service.start({...input,expectedRevision:w.revision});await service.cancel(input.weekStart);assert.equal(service.get(input.weekStart).job.status,'cancelled');assert.equal(service.get(input.weekStart).week.id,w.id);db.prepare('UPDATE kv SET v=? WHERE k=?').run(JSON.stringify({weekStart:input.weekStart,status:'running'}),`shopping.meals.job.${input.weekStart}`);createMealService({db,config:()=>config,localWork});assert.equal(service.get(input.weekStart).job.status,'interrupted');});
test('ordinary food emphases bind to actual recent lab ranges, never invented diagnoses',async t=>{
 const db=fixture(t),today=new Date().toISOString().slice(0,10);
 saveLab(db,{id:'lipid',date:today,name:'Total cholesterol',value:'208',unit:'mg/dL',referenceHigh:200});
 const week=await make(db);assert.ok(week.recipes.every(r=>r.basisIds.includes('lab:lipid')));assert.match(week.recipes[0].healthNotes[0],/saved lipid results/);
 saveLab(db,{id:'lipid',date:today,name:'Total cholesterol',value:'180',unit:'mg/dL',referenceHigh:200});
 const normal=await make(db);assert.ok(normal.recipes.every(r=>!r.basisIds.includes('lab:lipid')));
 saveLab(db,{id:'unclear',date:today,name:'Vitamin D',value:'<20',unit:'ng/mL',referenceLow:30});
 const uncertain=await make(db);assert.ok(uncertain.recipes.every(r=>!r.basisIds.includes('lab:unclear')));
});
test('each displayed week includes its own generated groceries plus manual items',async t=>{
 const {getShopping}=await import('../core/shopping.mjs');const db=fixture(t);saveGroceryItem(db,{name:'Manual item',quantity:'1 item'});
 const first=await make(db);persist(db,first);build(db,first);
 const second=await make(db,samplePlan(),{input:{...input,weekStart:'2026-09-21'}});persist(db,second);build(db,second);
 assert.equal(getShopping(db).items.length,7);assert.equal(getShopping(db,{weekStart:'2026-09-14'}).items.length,4);assert.equal(getShopping(db,{weekStart:'2026-09-21'}).items.length,4);
});
