import test from 'node:test';import assert from 'node:assert/strict';
import {monthList,presetRange,analyzeMoney,merchantName,exportRowsCsv} from '../ui/lib/money-analysis.js';
const base={date:'2026-08-10',currency:'USD',status:'confirmed',kind:'expense',category:'Dining',description:'Cafe'};
const row=(id,amountCents,extra={})=>({...base,id,amountCents,...extra});
const range={start:'2026-08-01',end:'2026-09-30',currency:'USD'};
test('month boundaries, leap days and invalid custom ranges',()=>{assert.deepEqual(monthList('2024-02-29','2024-03-01'),['2024-02','2024-03']);assert.throws(()=>monthList('2026-02-29','2026-03-01'));assert.throws(()=>monthList('2026-09-01','2026-08-01'));assert.throws(()=>monthList('2020-01-01','2026-01-01'));assert.deepEqual(presetRange('last-month','2026-01-12'),{start:'2025-12-01',end:'2025-12-31'});});
test('cross-month purchases reconcile; transfers, excluded rows, currencies and dates stay separate',()=>{const a=analyzeMoney([row('a',-1000),row('b',-2500,{date:'2026-09-04'}),row('c',500,{kind:'income'}),row('d',90000,{kind:'transfer'}),row('e',-999,{status:'excluded'}),row('f',-777,{currency:'EUR'}),row('g',-666,{date:'2026-10-01'})],range);assert.equal(a.total,3500);assert.equal(a.moneyIn,500);assert.equal(a.net,-3000);assert.equal(a.categories.reduce((n,c)=>n+c.total,0),3500);assert.equal(a.days.at(-1).cumulative,3500);assert.deepEqual(a.months.map(m=>m.total),[1000,2500]);assert.equal(a.transfers.length,1);});
test('recurring totals count actual charges separately from uncertain subscriptions',()=>{const a=analyzeMoney([row('a',-1299,{description:'SPOTIFY XXXX',category:'Subscriptions & recurring bills'}),row('b',-1299,{date:'2026-09-04',description:'SPOTIFY YYYY',category:'Subscriptions & recurring bills'}),row('c',-8147,{description:'RYTHM HEALTH',category:'Possible subscriptions — confirm'}),row('d',-1000)],range);assert.equal(a.subscriptionTotal,2598);assert.equal(a.possibleTotal,8147);assert.equal(a.subscriptions.length,2);assert.equal(a.subscriptions.find(s=>s.name==='Spotify').rows.length,2);});
test('empty periods remain zero and never produce NaN',()=>{const a=analyzeMoney([],range);assert.equal(a.total,0);assert.equal(a.average,0);assert.deepEqual(a.categories,[]);assert.equal(a.largest,null);assert.ok(a.days.every(d=>d.total===0));});
test('merchant grouping preserves separate purchases and source descriptions',()=>{const source='AplPay CHICK-FIL-A #01487  INDIANAPOLIS IN';const a=analyzeMoney([row('a',-100,{description:source}),row('b',-200,{description:'CHICK-FIL-A #04673  WESTFIELD IN'})],range);assert.equal(a.merchants.length,1);assert.equal(a.merchants[0].total,300);assert.equal(a.rows[0].description,source);assert.equal(merchantName('Unfamiliar vendor  CITY'),'Unfamiliar vendor');});
test('exports quote untrusted spreadsheet text and preserve amounts',()=>{const csv=exportRowsCsv([row('a',-1234,{description:'=DANGEROUS("x")'})]);assert.ok(csv.includes("'="));assert.ok(csv.includes('12.34'));assert.ok(csv.includes('""x""'));});

test('categorized recurring groups preserve account and workspace boundaries',()=>{const a=analyzeMoney([row('a',-1299,{entityId:'personal',accountId:'card1',description:'SPOTIFY',category:'Recurring bill'}),row('b',-1299,{entityId:'company',accountId:'card2',description:'SPOTIFY',category:'Recurring bill'})],range);assert.equal(a.subscriptions.length,2);assert.equal(a.subscriptionTotal,2598);});
